// Auto-generated by Supabase CLI — DO NOT EDIT
// Regenerate: npm run supabase:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      activity_log: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          ip_address: unknown
          metadata: Json | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          ip_address?: unknown
          metadata?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          ip_address?: unknown
          metadata?: Json | null
        }
        Relationships: [
          {
            foreignKeyName: "activity_log_actor_id_fkey"
            columns: ["actor_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      assessments: {
        Row: {
          ai_evaluation: Json | null
          ai_score: number | null
          candidate_id: string
          challenge_description: string
          challenge_generated_by: string | null
          created_at: string
          deadline_at: string | null
          id: string
          job_id: string | null
          status: string
          submission_text: string | null
          submission_url: string | null
          submitted_at: string | null
          type: string
          updated_at: string
        }
        Insert: {
          ai_evaluation?: Json | null
          ai_score?: number | null
          candidate_id: string
          challenge_description: string
          challenge_generated_by?: string | null
          created_at?: string
          deadline_at?: string | null
          id?: string
          job_id?: string | null
          status?: string
          submission_text?: string | null
          submission_url?: string | null
          submitted_at?: string | null
          type: string
          updated_at?: string
        }
        Update: {
          ai_evaluation?: Json | null
          ai_score?: number | null
          candidate_id?: string
          challenge_description?: string
          challenge_generated_by?: string | null
          created_at?: string
          deadline_at?: string | null
          id?: string
          job_id?: string | null
          status?: string
          submission_text?: string | null
          submission_url?: string | null
          submitted_at?: string | null
          type?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "assessments_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "assessments_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      candidates: {
        Row: {
          availability_date: string | null
          created_at: string
          cultural_score: number | null
          cv_embedding: string | null
          cv_text: string | null
          cv_url: string | null
          experience_score: number | null
          id: string
          intro_video_transcript: string | null
          intro_video_translations: Json | null
          intro_video_url: string | null
          transcript_json: Json | null
          translation_json: Json | null
          linkedin_raw_json: Json | null
          linkedin_scraped_at: string | null
          linkedin_url: string | null
          location_city: string | null
          location_country: string
          overall_score: number | null
          primary_role: string | null
          profile_scraped: boolean
          profile_id: string
          profile_summary: string | null
          relocation_countries: string[] | null
          relocation_willing: boolean
          salary_currency: string | null
          salary_expectation_max: number | null
          salary_expectation_min: number | null
          seniority: Database["public"]["Enums"]["seniority_level"] | null
          skills_score: number | null
          status: Database["public"]["Enums"]["candidate_status"]
          tech_stack: string[]
          updated_at: string
          years_experience: number | null
        }
        Insert: {
          availability_date?: string | null
          created_at?: string
          cultural_score?: number | null
          cv_embedding?: string | null
          cv_text?: string | null
          cv_url?: string | null
          experience_score?: number | null
          id?: string
          intro_video_transcript?: string | null
          intro_video_translations?: Json | null
          intro_video_url?: string | null
          transcript_json?: Json | null
          translation_json?: Json | null
          linkedin_raw_json?: Json | null
          linkedin_scraped_at?: string | null
          linkedin_url?: string | null
          location_city?: string | null
          location_country?: string
          overall_score?: number | null
          primary_role?: string | null
          profile_scraped?: boolean
          profile_id: string
          profile_summary?: string | null
          relocation_countries?: string[] | null
          relocation_willing?: boolean
          salary_currency?: string | null
          salary_expectation_max?: number | null
          salary_expectation_min?: number | null
          seniority?: Database["public"]["Enums"]["seniority_level"] | null
          skills_score?: number | null
          status?: Database["public"]["Enums"]["candidate_status"]
          tech_stack?: string[]
          updated_at?: string
          years_experience?: number | null
        }
        Update: {
          availability_date?: string | null
          created_at?: string
          cultural_score?: number | null
          cv_embedding?: string | null
          cv_text?: string | null
          cv_url?: string | null
          experience_score?: number | null
          id?: string
          intro_video_transcript?: string | null
          intro_video_translations?: Json | null
          intro_video_url?: string | null
          transcript_json?: Json | null
          translation_json?: Json | null
          linkedin_raw_json?: Json | null
          linkedin_scraped_at?: string | null
          linkedin_url?: string | null
          location_city?: string | null
          location_country?: string
          overall_score?: number | null
          primary_role?: string | null
          profile_scraped?: boolean
          profile_id?: string
          profile_summary?: string | null
          relocation_countries?: string[] | null
          relocation_willing?: boolean
          salary_currency?: string | null
          salary_expectation_max?: number | null
          salary_expectation_min?: number | null
          seniority?: Database["public"]["Enums"]["seniority_level"] | null
          skills_score?: number | null
          status?: Database["public"]["Enums"]["candidate_status"]
          tech_stack?: string[]
          updated_at?: string
          years_experience?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "candidates_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      companies: {
        Row: {
          company_size: string | null
          country: string
          created_at: string
          description: string | null
          email: string
          id: string
          industry: string | null
          logo_url: string | null
          name: string
          owner_id: string
          plan_tier: Database["public"]["Enums"]["plan_tier"]
          slug: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          updated_at: string
          verified: boolean
          website: string | null
        }
        Insert: {
          company_size?: string | null
          country?: string
          created_at?: string
          description?: string | null
          email: string
          id?: string
          industry?: string | null
          logo_url?: string | null
          name: string
          owner_id: string
          plan_tier?: Database["public"]["Enums"]["plan_tier"]
          slug: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          verified?: boolean
          website?: string | null
        }
        Update: {
          company_size?: string | null
          country?: string
          created_at?: string
          description?: string | null
          email?: string
          id?: string
          industry?: string | null
          logo_url?: string | null
          name?: string
          owner_id?: string
          plan_tier?: Database["public"]["Enums"]["plan_tier"]
          slug?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          updated_at?: string
          verified?: boolean
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "companies_owner_id_fkey"
            columns: ["owner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      contracts: {
        Row: {
          candidate_id: string
          company_id: string
          contract_type: Database["public"]["Enums"]["contract_type"]
          created_at: string
          end_date: string | null
          fee_base_salary: number | null
          fee_payment_schedule: Json | null
          fee_percentage: number | null
          fee_total_amount: number | null
          guarantee_end: string | null
          guarantee_start: string | null
          guarantee_status: string | null
          id: string
          job_id: string
          monthly_markup_pct: number | null
          monthly_salary: number | null
          monthly_total: number | null
          relocation_fee: number | null
          signed_at: string | null
          start_date: string | null
          status: Database["public"]["Enums"]["contract_status"]
          updated_at: string
        }
        Insert: {
          candidate_id: string
          company_id: string
          contract_type: Database["public"]["Enums"]["contract_type"]
          created_at?: string
          end_date?: string | null
          fee_base_salary?: number | null
          fee_payment_schedule?: Json | null
          fee_percentage?: number | null
          fee_total_amount?: number | null
          guarantee_end?: string | null
          guarantee_start?: string | null
          guarantee_status?: string | null
          id?: string
          job_id: string
          monthly_markup_pct?: number | null
          monthly_salary?: number | null
          monthly_total?: number | null
          relocation_fee?: number | null
          signed_at?: string | null
          start_date?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          updated_at?: string
        }
        Update: {
          candidate_id?: string
          company_id?: string
          contract_type?: Database["public"]["Enums"]["contract_type"]
          created_at?: string
          end_date?: string | null
          fee_base_salary?: number | null
          fee_payment_schedule?: Json | null
          fee_percentage?: number | null
          fee_total_amount?: number | null
          guarantee_end?: string | null
          guarantee_start?: string | null
          guarantee_status?: string | null
          id?: string
          job_id?: string
          monthly_markup_pct?: number | null
          monthly_salary?: number | null
          monthly_total?: number | null
          relocation_fee?: number | null
          signed_at?: string | null
          start_date?: string | null
          status?: Database["public"]["Enums"]["contract_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contracts_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "contracts_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      interviews: {
        Row: {
          ai_feedback: Json | null
          ai_model_used: string | null
          ai_score: number | null
          candidate_id: string
          completed_at: string | null
          created_at: string
          deadline_at: string | null
          human_approved: boolean | null
          human_notes: string | null
          human_reviewer_id: string | null
          id: string
          job_id: string | null
          matching_id: string | null
          questions: Json
          status: Database["public"]["Enums"]["interview_status"]
          transcript_language: string | null
          transcript_original: string | null
          translations: Json | null
          updated_at: string
          video_duration_sec: number | null
          video_url: string | null
        }
        Insert: {
          ai_feedback?: Json | null
          ai_model_used?: string | null
          ai_score?: number | null
          candidate_id: string
          completed_at?: string | null
          created_at?: string
          deadline_at?: string | null
          human_approved?: boolean | null
          human_notes?: string | null
          human_reviewer_id?: string | null
          id?: string
          job_id?: string | null
          matching_id?: string | null
          questions?: Json
          status?: Database["public"]["Enums"]["interview_status"]
          transcript_language?: string | null
          transcript_original?: string | null
          translations?: Json | null
          updated_at?: string
          video_duration_sec?: number | null
          video_url?: string | null
        }
        Update: {
          ai_feedback?: Json | null
          ai_model_used?: string | null
          ai_score?: number | null
          candidate_id?: string
          completed_at?: string | null
          created_at?: string
          deadline_at?: string | null
          human_approved?: boolean | null
          human_notes?: string | null
          human_reviewer_id?: string | null
          id?: string
          job_id?: string | null
          matching_id?: string | null
          questions?: Json
          status?: Database["public"]["Enums"]["interview_status"]
          transcript_language?: string | null
          transcript_original?: string | null
          translations?: Json | null
          updated_at?: string
          video_duration_sec?: number | null
          video_url?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "interviews_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interviews_human_reviewer_id_fkey"
            columns: ["human_reviewer_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interviews_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "interviews_matching_id_fkey"
            columns: ["matching_id"]
            isOneToOne: false
            referencedRelation: "matchings"
            referencedColumns: ["id"]
          },
        ]
      }
      jobs: {
        Row: {
          assessment_type: string | null
          benefits: Json | null
          closes_at: string | null
          company_id: string
          contract_type: Database["public"]["Enums"]["contract_type"]
          created_at: string
          created_by: string
          custom_interview_questions: Json | null
          description: string | null
          fee_percentage: number | null
          filled_at: string | null
          id: string
          jd_embedding: string | null
          jd_extracted_text: string | null
          jd_pdf_url: string | null
          jd_source_url: string | null
          location_city: string | null
          location_country: string | null
          monthly_markup_percentage: number | null
          nice_to_have_stack: string[] | null
          published_at: string | null
          relocation_budget: number | null
          relocation_support: boolean | null
          remote: boolean
          required_stack: string[]
          salary_currency: string | null
          salary_max: number | null
          salary_min: number | null
          seniority: Database["public"]["Enums"]["seniority_level"]
          slug: string
          status: Database["public"]["Enums"]["job_status"]
          title: string
          updated_at: string
        }
        Insert: {
          assessment_type?: string | null
          benefits?: Json | null
          closes_at?: string | null
          company_id: string
          contract_type?: Database["public"]["Enums"]["contract_type"]
          created_at?: string
          created_by: string
          custom_interview_questions?: Json | null
          description?: string | null
          fee_percentage?: number | null
          filled_at?: string | null
          id?: string
          jd_embedding?: string | null
          jd_extracted_text?: string | null
          jd_pdf_url?: string | null
          jd_source_url?: string | null
          location_city?: string | null
          location_country?: string | null
          monthly_markup_percentage?: number | null
          nice_to_have_stack?: string[] | null
          published_at?: string | null
          relocation_budget?: number | null
          relocation_support?: boolean | null
          remote?: boolean
          required_stack?: string[]
          salary_currency?: string | null
          salary_max?: number | null
          salary_min?: number | null
          seniority?: Database["public"]["Enums"]["seniority_level"]
          slug: string
          status?: Database["public"]["Enums"]["job_status"]
          title: string
          updated_at?: string
        }
        Update: {
          assessment_type?: string | null
          benefits?: Json | null
          closes_at?: string | null
          company_id?: string
          contract_type?: Database["public"]["Enums"]["contract_type"]
          created_at?: string
          created_by?: string
          custom_interview_questions?: Json | null
          description?: string | null
          fee_percentage?: number | null
          filled_at?: string | null
          id?: string
          jd_embedding?: string | null
          jd_extracted_text?: string | null
          jd_pdf_url?: string | null
          jd_source_url?: string | null
          location_city?: string | null
          location_country?: string | null
          monthly_markup_percentage?: number | null
          nice_to_have_stack?: string[] | null
          published_at?: string | null
          relocation_budget?: number | null
          relocation_support?: boolean | null
          remote?: boolean
          required_stack?: string[]
          salary_currency?: string | null
          salary_max?: number | null
          salary_min?: number | null
          seniority?: Database["public"]["Enums"]["seniority_level"]
          slug?: string
          status?: Database["public"]["Enums"]["job_status"]
          title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "jobs_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "jobs_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      matchings: {
        Row: {
          candidate_id: string
          company_feedback: string | null
          created_at: string
          explanation_json: Json | null
          id: string
          job_id: string
          llm_models_used: string[] | null
          notified_candidate_at: string | null
          notified_company_at: string | null
          rejection_category: string | null
          rejection_reason: string | null
          score_cultural: number | null
          score_details: Json | null
          score_overall: number
          score_semantic: number | null
          score_seniority: number | null
          score_specialized: number | null
          score_skills: number | null
          score_tech: number | null
          share_expires_at: string | null
          share_token: string | null
          share_viewed_at: string | null
          status: Database["public"]["Enums"]["match_status"]
          updated_at: string
        }
        Insert: {
          candidate_id: string
          company_feedback?: string | null
          created_at?: string
          explanation_json?: Json | null
          id?: string
          job_id: string
          llm_models_used?: string[] | null
          notified_candidate_at?: string | null
          notified_company_at?: string | null
          rejection_category?: string | null
          rejection_reason?: string | null
          score_cultural?: number | null
          score_details?: Json | null
          score_overall?: number
          score_semantic?: number | null
          score_seniority?: number | null
          score_specialized?: number | null
          score_skills?: number | null
          score_tech?: number | null
          share_expires_at?: string | null
          share_token?: string | null
          share_viewed_at?: string | null
          status?: Database["public"]["Enums"]["match_status"]
          updated_at?: string
        }
        Update: {
          candidate_id?: string
          company_feedback?: string | null
          created_at?: string
          explanation_json?: Json | null
          id?: string
          job_id?: string
          llm_models_used?: string[] | null
          notified_candidate_at?: string | null
          notified_company_at?: string | null
          rejection_category?: string | null
          rejection_reason?: string | null
          score_cultural?: number | null
          score_details?: Json | null
          score_overall?: number
          score_semantic?: number | null
          score_seniority?: number | null
          score_specialized?: number | null
          score_skills?: number | null
          score_tech?: number | null
          share_expires_at?: string | null
          share_token?: string | null
          share_viewed_at?: string | null
          status?: Database["public"]["Enums"]["match_status"]
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "matchings_candidate_id_fkey"
            columns: ["candidate_id"]
            isOneToOne: false
            referencedRelation: "candidates"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "matchings_job_id_fkey"
            columns: ["job_id"]
            isOneToOne: false
            referencedRelation: "jobs"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          action_url: string | null
          body: string
          channel: Database["public"]["Enums"]["notification_channel"]
          created_at: string
          delivered_at: string | null
          failed_reason: string | null
          id: string
          metadata: Json | null
          read_at: string | null
          recipient_id: string
          resend_message_id: string | null
          sent_at: string | null
          title: string
          whatsapp_message_id: string | null
        }
        Insert: {
          action_url?: string | null
          body: string
          channel?: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          delivered_at?: string | null
          failed_reason?: string | null
          id?: string
          metadata?: Json | null
          read_at?: string | null
          recipient_id: string
          resend_message_id?: string | null
          sent_at?: string | null
          title: string
          whatsapp_message_id?: string | null
        }
        Update: {
          action_url?: string | null
          body?: string
          channel?: Database["public"]["Enums"]["notification_channel"]
          created_at?: string
          delivered_at?: string | null
          failed_reason?: string | null
          id?: string
          metadata?: Json | null
          read_at?: string | null
          recipient_id?: string
          resend_message_id?: string | null
          sent_at?: string | null
          title?: string
          whatsapp_message_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "notifications_recipient_id_fkey"
            columns: ["recipient_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      payments: {
        Row: {
          amount: number
          billing_period_end: string | null
          billing_period_start: string | null
          company_id: string
          contract_id: string
          created_at: string
          currency: string
          description: string | null
          failed_reason: string | null
          id: string
          is_recurring: boolean | null
          paid_at: string | null
          payment_method: string
          revolut_transaction_id: string | null
          status: Database["public"]["Enums"]["payment_status"]
          stripe_invoice_id: string | null
          stripe_payment_intent_id: string | null
          updated_at: string
          wise_transfer_id: string | null
        }
        Insert: {
          amount: number
          billing_period_end?: string | null
          billing_period_start?: string | null
          company_id: string
          contract_id: string
          created_at?: string
          currency?: string
          description?: string | null
          failed_reason?: string | null
          id?: string
          is_recurring?: boolean | null
          paid_at?: string | null
          payment_method?: string
          revolut_transaction_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          stripe_invoice_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          wise_transfer_id?: string | null
        }
        Update: {
          amount?: number
          billing_period_end?: string | null
          billing_period_start?: string | null
          company_id?: string
          contract_id?: string
          created_at?: string
          currency?: string
          description?: string | null
          failed_reason?: string | null
          id?: string
          is_recurring?: boolean | null
          paid_at?: string | null
          payment_method?: string
          revolut_transaction_id?: string | null
          status?: Database["public"]["Enums"]["payment_status"]
          stripe_invoice_id?: string | null
          stripe_payment_intent_id?: string | null
          updated_at?: string
          wise_transfer_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "payments_company_id_fkey"
            columns: ["company_id"]
            isOneToOne: false
            referencedRelation: "companies"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "payments_contract_id_fkey"
            columns: ["contract_id"]
            isOneToOne: false
            referencedRelation: "contracts"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          avatar_url: string | null
          created_at: string
          data_retention_until: string | null
          email: string
          full_name: string
          gdpr_consent: boolean
          gdpr_consent_at: string | null
          id: string
          last_active_at: string | null
          lgpd_consent: boolean
          lgpd_consent_at: string | null
          phone: string | null
          preferred_language: string
          role: Database["public"]["Enums"]["user_role"]
          timezone: string | null
          updated_at: string
        }
        Insert: {
          avatar_url?: string | null
          created_at?: string
          data_retention_until?: string | null
          email: string
          full_name: string
          gdpr_consent?: boolean
          gdpr_consent_at?: string | null
          id: string
          last_active_at?: string | null
          lgpd_consent?: boolean
          lgpd_consent_at?: string | null
          phone?: string | null
          preferred_language?: string
          role?: Database["public"]["Enums"]["user_role"]
          timezone?: string | null
          updated_at?: string
        }
        Update: {
          avatar_url?: string | null
          created_at?: string
          data_retention_until?: string | null
          email?: string
          full_name?: string
          gdpr_consent?: boolean
          gdpr_consent_at?: string | null
          id?: string
          last_active_at?: string | null
          lgpd_consent?: boolean
          lgpd_consent_at?: string | null
          phone?: string | null
          preferred_language?: string
          role?: Database["public"]["Enums"]["user_role"]
          timezone?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      translations: {
        Row: {
          created_at: string
          de: string | null
          en: string | null
          es: string | null
          fr: string | null
          id: string
          it: string | null
          key: string
          namespace: string
          pt: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          de?: string | null
          en?: string | null
          es?: string | null
          fr?: string | null
          id?: string
          it?: string | null
          key: string
          namespace?: string
          pt?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          de?: string | null
          en?: string | null
          es?: string | null
          fr?: string | null
          id?: string
          it?: string | null
          key?: string
          namespace?: string
          pt?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      user_preferences: {
        Row: {
          email_digest: string | null
          id: string
          notifications_enabled: boolean | null
          preferences: Json | null
          sidebar_collapsed: boolean | null
          theme: string | null
          updated_at: string
          user_id: string
        }
        Insert: {
          email_digest?: string | null
          id?: string
          notifications_enabled?: boolean | null
          preferences?: Json | null
          sidebar_collapsed?: boolean | null
          theme?: string | null
          updated_at?: string
          user_id: string
        }
        Update: {
          email_digest?: string | null
          id?: string
          notifications_enabled?: boolean | null
          preferences?: Json | null
          sidebar_collapsed?: boolean | null
          theme?: string | null
          updated_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "user_preferences_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: true
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_share_link: {
        Args: { p_matching_id: string }
        Returns: { expires_at: string; token: string }[]
      }
      match_candidates_to_job: {
        Args: {
          job_embedding: string
          match_threshold?: number
          max_results?: number
        }
        Returns: {
          candidate_id: string
          candidate_name: string
          similarity: number
        }[]
      }
      validate_share_link: {
        Args: { p_token: string }
        Returns: {
          candidate_name: string
          is_valid: boolean
          job_title: string
          matching_id: string
        }[]
      }
    }
    Enums: {
      candidate_status: "active" | "interviewing" | "matched" | "hired" | "inactive" | "blacklisted"
      contract_status: "draft" | "pending_signature" | "signed" | "active" | "completed" | "cancelled"
      contract_type: "fee_15pct" | "service_markup_40pct"
      interview_status: "pending" | "questions_sent" | "video_submitted" | "transcribed" | "scored" | "approved" | "rejected"
      job_status: "draft" | "active" | "paused" | "closed" | "filled"
      match_status: "pending" | "sent_to_company" | "viewed" | "interview_requested" | "rejected" | "accepted" | "hired"
      notification_channel: "email" | "whatsapp" | "push" | "in_app"
      payment_status: "pending" | "processing" | "paid" | "failed" | "refunded"
      plan_tier: "free" | "starter" | "professional" | "enterprise"
      seniority_level: "junior" | "mid" | "senior" | "lead" | "principal" | "c_level"
      user_role: "candidate" | "company" | "admin_master" | "admin_recruiter" | "instructor"
    }
  }
}
